# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1462, 721)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.settings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_3 = QtWidgets.QFrame(self.settings)
        self.line_3.setLineWidth(3)
        self.line_3.setMidLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_arch_settings = QtWidgets.QLabel(self.settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_arch_settings.setFont(font)
        self.label_arch_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_arch_settings.setObjectName("label_arch_settings")
        self.verticalLayout_2.addWidget(self.label_arch_settings)
        self.label_arch_processor = QtWidgets.QLabel(self.settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_arch_processor.setFont(font)
        self.label_arch_processor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_arch_processor.setObjectName("label_arch_processor")
        self.verticalLayout_2.addWidget(self.label_arch_processor)
        self.comboBox_arch = QtWidgets.QComboBox(self.settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_arch.setFont(font)
        self.comboBox_arch.setObjectName("comboBox_arch")
        self.comboBox_arch.addItem("")
        self.comboBox_arch.addItem("")
        self.comboBox_arch.addItem("")
        self.comboBox_arch.addItem("")
        self.comboBox_arch.addItem("")
        self.comboBox_arch.addItem("")
        self.comboBox_arch.addItem("")
        self.comboBox_arch.addItem("")
        self.comboBox_arch.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_arch)
        self.checkBox_arch_macro = QtWidgets.QCheckBox(self.settings)
        self.checkBox_arch_macro.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_arch_macro.setFont(font)
        self.checkBox_arch_macro.setChecked(True)
        self.checkBox_arch_macro.setObjectName("checkBox_arch_macro")
        self.verticalLayout_2.addWidget(self.checkBox_arch_macro)
        self.checkBox_arch_micro = QtWidgets.QCheckBox(self.settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_arch_micro.setFont(font)
        self.checkBox_arch_micro.setChecked(True)
        self.checkBox_arch_micro.setObjectName("checkBox_arch_micro")
        self.verticalLayout_2.addWidget(self.checkBox_arch_micro)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_user_arch = QtWidgets.QLabel(self.settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_user_arch.setFont(font)
        self.label_user_arch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_arch.setObjectName("label_user_arch")
        self.verticalLayout_2.addWidget(self.label_user_arch)
        self.label_user_micro = QtWidgets.QLabel(self.settings)
        self.label_user_micro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_micro.setObjectName("label_user_micro")
        self.verticalLayout_2.addWidget(self.label_user_micro)
        self.comboBox_arch_micro = QtWidgets.QComboBox(self.settings)
        self.comboBox_arch_micro.setObjectName("comboBox_arch_micro")
        self.comboBox_arch_micro.addItem("")
        self.comboBox_arch_micro.addItem("")
        self.comboBox_arch_micro.addItem("")
        self.comboBox_arch_micro.addItem("")
        self.comboBox_arch_micro.addItem("")
        self.comboBox_arch_micro.addItem("")
        self.comboBox_arch_micro.addItem("")
        self.comboBox_arch_micro.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_arch_micro)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.settings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_macro_fusion_settings = QtWidgets.QLabel(self.settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_macro_fusion_settings.setFont(font)
        self.label_macro_fusion_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_macro_fusion_settings.setObjectName("label_macro_fusion_settings")
        self.verticalLayout_3.addWidget(self.label_macro_fusion_settings)
        self.label_macro_pairs_settings = QtWidgets.QLabel(self.settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_macro_pairs_settings.setFont(font)
        self.label_macro_pairs_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_macro_pairs_settings.setObjectName("label_macro_pairs_settings")
        self.verticalLayout_3.addWidget(self.label_macro_pairs_settings)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_macro_first_pair = QtWidgets.QLabel(self.settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_macro_first_pair.setFont(font)
        self.label_macro_first_pair.setAlignment(QtCore.Qt.AlignCenter)
        self.label_macro_first_pair.setObjectName("label_macro_first_pair")
        self.horizontalLayout_5.addWidget(self.label_macro_first_pair)
        self.label_macro_second_pair = QtWidgets.QLabel(self.settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_macro_second_pair.setFont(font)
        self.label_macro_second_pair.setAlignment(QtCore.Qt.AlignCenter)
        self.label_macro_second_pair.setObjectName("label_macro_second_pair")
        self.horizontalLayout_5.addWidget(self.label_macro_second_pair)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea_macro_first_pair = QtWidgets.QScrollArea(self.settings)
        self.scrollArea_macro_first_pair.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_macro_first_pair.sizePolicy().hasHeightForWidth())
        self.scrollArea_macro_first_pair.setSizePolicy(sizePolicy)
        self.scrollArea_macro_first_pair.setWidgetResizable(True)
        self.scrollArea_macro_first_pair.setObjectName("scrollArea_macro_first_pair")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 269, 350))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioButton_ADD = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_ADD.sizePolicy().hasHeightForWidth())
        self.radioButton_ADD.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_ADD.setFont(font)
        self.radioButton_ADD.setObjectName("radioButton_ADD")
        self.verticalLayout_9.addWidget(self.radioButton_ADD)
        self.radioButton_SUB = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_SUB.setFont(font)
        self.radioButton_SUB.setObjectName("radioButton_SUB")
        self.verticalLayout_9.addWidget(self.radioButton_SUB)
        self.radioButton_ADC = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_ADC.setObjectName("radioButton_ADC")
        self.verticalLayout_9.addWidget(self.radioButton_ADC)
        self.radioButton_SBB = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_SBB.setObjectName("radioButton_SBB")
        self.verticalLayout_9.addWidget(self.radioButton_SBB)
        self.radioButton_INC = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_INC.setObjectName("radioButton_INC")
        self.verticalLayout_9.addWidget(self.radioButton_INC)
        self.radioButton_DEC = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_DEC.setObjectName("radioButton_DEC")
        self.verticalLayout_9.addWidget(self.radioButton_DEC)
        self.radioButton_CMP = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_CMP.setCheckable(True)
        self.radioButton_CMP.setChecked(False)
        self.radioButton_CMP.setObjectName("radioButton_CMP")
        self.verticalLayout_9.addWidget(self.radioButton_CMP)
        self.radioButton_TEST = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_TEST.setChecked(False)
        self.radioButton_TEST.setAutoExclusive(True)
        self.radioButton_TEST.setObjectName("radioButton_TEST")
        self.verticalLayout_9.addWidget(self.radioButton_TEST)
        self.radioButton_AND = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_AND.setObjectName("radioButton_AND")
        self.verticalLayout_9.addWidget(self.radioButton_AND)
        self.radioButton_OR = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_OR.setObjectName("radioButton_OR")
        self.verticalLayout_9.addWidget(self.radioButton_OR)
        self.radioButton_XOR = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_XOR.setCheckable(True)
        self.radioButton_XOR.setChecked(False)
        self.radioButton_XOR.setObjectName("radioButton_XOR")
        self.verticalLayout_9.addWidget(self.radioButton_XOR)
        self.radioButton_NOT = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_NOT.setObjectName("radioButton_NOT")
        self.verticalLayout_9.addWidget(self.radioButton_NOT)
        self.radioButton_NEG = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_NEG.setObjectName("radioButton_NEG")
        self.verticalLayout_9.addWidget(self.radioButton_NEG)
        self.scrollArea_macro_first_pair.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_4.addWidget(self.scrollArea_macro_first_pair)
        self.scrollArea_macro_second_pair = QtWidgets.QScrollArea(self.settings)
        self.scrollArea_macro_second_pair.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_macro_second_pair.sizePolicy().hasHeightForWidth())
        self.scrollArea_macro_second_pair.setSizePolicy(sizePolicy)
        self.scrollArea_macro_second_pair.setWidgetResizable(True)
        self.scrollArea_macro_second_pair.setObjectName("scrollArea_macro_second_pair")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -644, 269, 896))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBox_JA = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JA.setCheckable(True)
        self.checkBox_JA.setTristate(False)
        self.checkBox_JA.setObjectName("checkBox_JA")
        self.verticalLayout_13.addWidget(self.checkBox_JA)
        self.checkBox_JNA = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNA.setObjectName("checkBox_JNA")
        self.verticalLayout_13.addWidget(self.checkBox_JNA)
        self.checkBox_JAE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JAE.setObjectName("checkBox_JAE")
        self.verticalLayout_13.addWidget(self.checkBox_JAE)
        self.checkBox_JNAE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNAE.setObjectName("checkBox_JNAE")
        self.verticalLayout_13.addWidget(self.checkBox_JNAE)
        self.checkBox_JB = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JB.setObjectName("checkBox_JB")
        self.verticalLayout_13.addWidget(self.checkBox_JB)
        self.checkBox_JNB = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNB.setObjectName("checkBox_JNB")
        self.verticalLayout_13.addWidget(self.checkBox_JNB)
        self.checkBox_JBE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JBE.setObjectName("checkBox_JBE")
        self.verticalLayout_13.addWidget(self.checkBox_JBE)
        self.checkBox_JNBE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNBE.setObjectName("checkBox_JNBE")
        self.verticalLayout_13.addWidget(self.checkBox_JNBE)
        self.checkBox_JC = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JC.setObjectName("checkBox_JC")
        self.verticalLayout_13.addWidget(self.checkBox_JC)
        self.checkBox_JNC = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNC.setObjectName("checkBox_JNC")
        self.verticalLayout_13.addWidget(self.checkBox_JNC)
        self.checkBox_JE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JE.setObjectName("checkBox_JE")
        self.verticalLayout_13.addWidget(self.checkBox_JE)
        self.checkBox_JNE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNE.setObjectName("checkBox_JNE")
        self.verticalLayout_13.addWidget(self.checkBox_JNE)
        self.checkBox_JG = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JG.setObjectName("checkBox_JG")
        self.verticalLayout_13.addWidget(self.checkBox_JG)
        self.checkBox_JNG = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNG.setObjectName("checkBox_JNG")
        self.verticalLayout_13.addWidget(self.checkBox_JNG)
        self.checkBox_JGE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JGE.setObjectName("checkBox_JGE")
        self.verticalLayout_13.addWidget(self.checkBox_JGE)
        self.checkBox_JNGE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNGE.setObjectName("checkBox_JNGE")
        self.verticalLayout_13.addWidget(self.checkBox_JNGE)
        self.checkBox_JL = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JL.setObjectName("checkBox_JL")
        self.verticalLayout_13.addWidget(self.checkBox_JL)
        self.checkBox_JNL = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNL.setObjectName("checkBox_JNL")
        self.verticalLayout_13.addWidget(self.checkBox_JNL)
        self.checkBox_JLE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JLE.setObjectName("checkBox_JLE")
        self.verticalLayout_13.addWidget(self.checkBox_JLE)
        self.checkBox_JNLE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNLE.setObjectName("checkBox_JNLE")
        self.verticalLayout_13.addWidget(self.checkBox_JNLE)
        self.checkBox_JS = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JS.setObjectName("checkBox_JS")
        self.verticalLayout_13.addWidget(self.checkBox_JS)
        self.checkBox_JNS = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNS.setObjectName("checkBox_JNS")
        self.verticalLayout_13.addWidget(self.checkBox_JNS)
        self.checkBox_JO = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JO.setObjectName("checkBox_JO")
        self.verticalLayout_13.addWidget(self.checkBox_JO)
        self.checkBox_JNO = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNO.setEnabled(True)
        self.checkBox_JNO.setCheckable(True)
        self.checkBox_JNO.setChecked(False)
        self.checkBox_JNO.setObjectName("checkBox_JNO")
        self.verticalLayout_13.addWidget(self.checkBox_JNO)
        self.checkBox_JP = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JP.setObjectName("checkBox_JP")
        self.verticalLayout_13.addWidget(self.checkBox_JP)
        self.checkBox_JNP = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNP.setObjectName("checkBox_JNP")
        self.verticalLayout_13.addWidget(self.checkBox_JNP)
        self.checkBox_JPO = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JPO.setObjectName("checkBox_JPO")
        self.verticalLayout_13.addWidget(self.checkBox_JPO)
        self.checkBox_JPE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JPE.setObjectName("checkBox_JPE")
        self.verticalLayout_13.addWidget(self.checkBox_JPE)
        self.checkBox_JZ = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JZ.setObjectName("checkBox_JZ")
        self.verticalLayout_13.addWidget(self.checkBox_JZ)
        self.checkBox_JNZ = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JNZ.setObjectName("checkBox_JNZ")
        self.verticalLayout_13.addWidget(self.checkBox_JNZ)
        self.checkBox_JCXZ = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JCXZ.setObjectName("checkBox_JCXZ")
        self.verticalLayout_13.addWidget(self.checkBox_JCXZ)
        self.checkBox_JECXZ = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JECXZ.setObjectName("checkBox_JECXZ")
        self.verticalLayout_13.addWidget(self.checkBox_JECXZ)
        self.checkBox_JRCXZ = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_JRCXZ.setObjectName("checkBox_JRCXZ")
        self.verticalLayout_13.addWidget(self.checkBox_JRCXZ)
        self.checkBox_LOOP = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_LOOP.setObjectName("checkBox_LOOP")
        self.verticalLayout_13.addWidget(self.checkBox_LOOP)
        self.scrollArea_macro_second_pair.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.scrollArea_macro_second_pair)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_macro_first_pair_operands = QtWidgets.QLabel(self.settings)
        self.label_macro_first_pair_operands.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_macro_first_pair_operands.setObjectName("label_macro_first_pair_operands")
        self.horizontalLayout_6.addWidget(self.label_macro_first_pair_operands)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scrollArea_macro_operands = QtWidgets.QScrollArea(self.settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_macro_operands.sizePolicy().hasHeightForWidth())
        self.scrollArea_macro_operands.setSizePolicy(sizePolicy)
        self.scrollArea_macro_operands.setWidgetResizable(True)
        self.scrollArea_macro_operands.setObjectName("scrollArea_macro_operands")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 563, 220))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.checkBox_Reg_Reg = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Reg_Reg.sizePolicy().hasHeightForWidth())
        self.checkBox_Reg_Reg.setSizePolicy(sizePolicy)
        self.checkBox_Reg_Reg.setObjectName("checkBox_Reg_Reg")
        self.verticalLayout_12.addWidget(self.checkBox_Reg_Reg)
        self.checkBox_Reg_Imm = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Reg_Imm.sizePolicy().hasHeightForWidth())
        self.checkBox_Reg_Imm.setSizePolicy(sizePolicy)
        self.checkBox_Reg_Imm.setObjectName("checkBox_Reg_Imm")
        self.verticalLayout_12.addWidget(self.checkBox_Reg_Imm)
        self.checkBox_Reg_Mem = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Reg_Mem.sizePolicy().hasHeightForWidth())
        self.checkBox_Reg_Mem.setSizePolicy(sizePolicy)
        self.checkBox_Reg_Mem.setObjectName("checkBox_Reg_Mem")
        self.verticalLayout_12.addWidget(self.checkBox_Reg_Mem)
        self.checkBox_Reg_RIP = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBox_Reg_RIP.setObjectName("checkBox_Reg_RIP")
        self.verticalLayout_12.addWidget(self.checkBox_Reg_RIP)
        self.checkBox_Mem_Imm = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBox_Mem_Imm.setObjectName("checkBox_Mem_Imm")
        self.verticalLayout_12.addWidget(self.checkBox_Mem_Imm)
        self.checkBox_Reg = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBox_Reg.setObjectName("checkBox_Reg")
        self.verticalLayout_12.addWidget(self.checkBox_Reg)
        self.checkBox_Mem = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBox_Mem.setObjectName("checkBox_Mem")
        self.verticalLayout_12.addWidget(self.checkBox_Mem)
        self.checkBox_RIP = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBox_RIP.setObjectName("checkBox_RIP")
        self.verticalLayout_12.addWidget(self.checkBox_RIP)
        self.scrollArea_macro_operands.setWidget(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_7.addWidget(self.scrollArea_macro_operands)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.label_macro_conditions = QtWidgets.QLabel(self.settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_macro_conditions.setFont(font)
        self.label_macro_conditions.setObjectName("label_macro_conditions")
        self.verticalLayout_3.addWidget(self.label_macro_conditions)
        self.scrollArea_macro_conditions = QtWidgets.QScrollArea(self.settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_macro_conditions.sizePolicy().hasHeightForWidth())
        self.scrollArea_macro_conditions.setSizePolicy(sizePolicy)
        self.scrollArea_macro_conditions.setSizeIncrement(QtCore.QSize(0, 0))
        self.scrollArea_macro_conditions.setBaseSize(QtCore.QSize(0, 0))
        self.scrollArea_macro_conditions.setWidgetResizable(True)
        self.scrollArea_macro_conditions.setObjectName("scrollArea_macro_conditions")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 565, 222))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox_16_Bit_Border_Start = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_16_Bit_Border_Start.setObjectName("checkBox_16_Bit_Border_Start")
        self.verticalLayout_11.addWidget(self.checkBox_16_Bit_Border_Start)
        self.checkBox_16_Bit_Border_Cross = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_16_Bit_Border_Cross.setFont(font)
        self.checkBox_16_Bit_Border_Cross.setObjectName("checkBox_16_Bit_Border_Cross")
        self.verticalLayout_11.addWidget(self.checkBox_16_Bit_Border_Cross)
        self.checkBox_Two_Pairs = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_Two_Pairs.setObjectName("checkBox_Two_Pairs")
        self.verticalLayout_11.addWidget(self.checkBox_Two_Pairs)
        self.checkBox_Transfer = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_Transfer.setObjectName("checkBox_Transfer")
        self.verticalLayout_11.addWidget(self.checkBox_Transfer)
        self.label_macro_mode = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_macro_mode.setFont(font)
        self.label_macro_mode.setObjectName("label_macro_mode")
        self.verticalLayout_11.addWidget(self.label_macro_mode)
        self.checkBox_16_Bit_Mode = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_16_Bit_Mode.setObjectName("checkBox_16_Bit_Mode")
        self.verticalLayout_11.addWidget(self.checkBox_16_Bit_Mode)
        self.checkBox_32_Bit_Mode = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_32_Bit_Mode.setObjectName("checkBox_32_Bit_Mode")
        self.verticalLayout_11.addWidget(self.checkBox_32_Bit_Mode)
        self.checkBox_64_Bit_Mode = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_64_Bit_Mode.setObjectName("checkBox_64_Bit_Mode")
        self.verticalLayout_11.addWidget(self.checkBox_64_Bit_Mode)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.scrollArea_macro_conditions.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_3.addWidget(self.scrollArea_macro_conditions)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.settings)
        self.line_2.setLineWidth(3)
        self.line_2.setMidLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_micro_fusion_settings = QtWidgets.QLabel(self.settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_micro_fusion_settings.sizePolicy().hasHeightForWidth())
        self.label_micro_fusion_settings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_micro_fusion_settings.setFont(font)
        self.label_micro_fusion_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_micro_fusion_settings.setObjectName("label_micro_fusion_settings")
        self.verticalLayout_7.addWidget(self.label_micro_fusion_settings)
        self.label_micro_pairs_settings = QtWidgets.QLabel(self.settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_micro_pairs_settings.sizePolicy().hasHeightForWidth())
        self.label_micro_pairs_settings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_micro_pairs_settings.setFont(font)
        self.label_micro_pairs_settings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_micro_pairs_settings.setObjectName("label_micro_pairs_settings")
        self.verticalLayout_7.addWidget(self.label_micro_pairs_settings)
        self.scrollArea_micro_pairs = QtWidgets.QScrollArea(self.settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_micro_pairs.sizePolicy().hasHeightForWidth())
        self.scrollArea_micro_pairs.setSizePolicy(sizePolicy)
        self.scrollArea_micro_pairs.setWidgetResizable(True)
        self.scrollArea_micro_pairs.setObjectName("scrollArea_micro_pairs")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 582, 268))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_Address_Write = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Address_Write.setFont(font)
        self.checkBox_Address_Write.setObjectName("checkBox_Address_Write")
        self.verticalLayout_8.addWidget(self.checkBox_Address_Write)
        self.checkBox_Read_Modify = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Read_Modify.setFont(font)
        self.checkBox_Read_Modify.setObjectName("checkBox_Read_Modify")
        self.verticalLayout_8.addWidget(self.checkBox_Read_Modify)
        self.checkBox_Read_Modify_Write = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Read_Modify_Write.setFont(font)
        self.checkBox_Read_Modify_Write.setObjectName("checkBox_Read_Modify_Write")
        self.verticalLayout_8.addWidget(self.checkBox_Read_Modify_Write)
        self.scrollArea_micro_pairs.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.scrollArea_micro_pairs)
        self.label_micro_conditions = QtWidgets.QLabel(self.settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_micro_conditions.sizePolicy().hasHeightForWidth())
        self.label_micro_conditions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_micro_conditions.setFont(font)
        self.label_micro_conditions.setObjectName("label_micro_conditions")
        self.verticalLayout_7.addWidget(self.label_micro_conditions)
        self.scrollArea_micro_conditions = QtWidgets.QScrollArea(self.settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_micro_conditions.sizePolicy().hasHeightForWidth())
        self.scrollArea_micro_conditions.setSizePolicy(sizePolicy)
        self.scrollArea_micro_conditions.setWidgetResizable(True)
        self.scrollArea_micro_conditions.setObjectName("scrollArea_micro_conditions")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 582, 267))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.checkBox_micro_Rip_Imm = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.checkBox_micro_Rip_Imm.setObjectName("checkBox_micro_Rip_Imm")
        self.verticalLayout_10.addWidget(self.checkBox_micro_Rip_Imm)
        self.label_micro_operated_registers = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_micro_operated_registers.setFont(font)
        self.label_micro_operated_registers.setObjectName("label_micro_operated_registers")
        self.verticalLayout_10.addWidget(self.label_micro_operated_registers)
        self.checkBox_micro_Reg = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_micro_Reg.setFont(font)
        self.checkBox_micro_Reg.setObjectName("checkBox_micro_Reg")
        self.verticalLayout_10.addWidget(self.checkBox_micro_Reg)
        self.checkBox_micro_Mem = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.checkBox_micro_Mem.setObjectName("checkBox_micro_Mem")
        self.verticalLayout_10.addWidget(self.checkBox_micro_Mem)
        self.checkBox_micro_Mmx = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_micro_Mmx.setFont(font)
        self.checkBox_micro_Mmx.setObjectName("checkBox_micro_Mmx")
        self.verticalLayout_10.addWidget(self.checkBox_micro_Mmx)
        self.checkBox_micro_Xmm = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_micro_Xmm.setFont(font)
        self.checkBox_micro_Xmm.setObjectName("checkBox_micro_Xmm")
        self.verticalLayout_10.addWidget(self.checkBox_micro_Xmm)
        self.checkBox_micro_Rip = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_micro_Rip.setFont(font)
        self.checkBox_micro_Rip.setObjectName("checkBox_micro_Rip")
        self.verticalLayout_10.addWidget(self.checkBox_micro_Rip)
        self.checkBox_micro_Imm = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_micro_Imm.setFont(font)
        self.checkBox_micro_Imm.setObjectName("checkBox_micro_Imm")
        self.verticalLayout_10.addWidget(self.checkBox_micro_Imm)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.scrollArea_micro_conditions.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_7.addWidget(self.scrollArea_micro_conditions)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.line_4 = QtWidgets.QFrame(self.settings)
        self.line_4.setLineWidth(3)
        self.line_4.setMidLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.tabWidget.addTab(self.settings, "")
        self.macro = QtWidgets.QWidget()
        self.macro.setObjectName("macro")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.macro)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_macro = QtWidgets.QPlainTextEdit(self.macro)
        self.textEdit_macro.setEnabled(True)
        self.textEdit_macro.setMouseTracking(False)
        self.textEdit_macro.setObjectName("textEdit_macro")
        self.horizontalLayout_2.addWidget(self.textEdit_macro)
        self.tableWidget_macro = QtWidgets.QTableWidget(self.macro)
        self.tableWidget_macro.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_macro.setAlternatingRowColors(False)
        self.tableWidget_macro.setColumnCount(0)
        self.tableWidget_macro.setObjectName("tableWidget_macro")
        self.tableWidget_macro.setRowCount(0)
        self.tableWidget_macro.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_macro.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_macro.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget_macro.horizontalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.tableWidget_macro)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_macro_template = QtWidgets.QLabel(self.macro)
        self.label_macro_template.setObjectName("label_macro_template")
        self.verticalLayout_4.addWidget(self.label_macro_template)
        self.comboBox_macro_template = QtWidgets.QComboBox(self.macro)
        self.comboBox_macro_template.setObjectName("comboBox_macro_template")
        self.comboBox_macro_template.addItem("")
        self.comboBox_macro_template.setItemText(0, "")
        self.verticalLayout_4.addWidget(self.comboBox_macro_template)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pushButton_simulate = QtWidgets.QPushButton(self.macro)
        self.pushButton_simulate.setObjectName("pushButton_simulate")
        self.horizontalLayout_3.addWidget(self.pushButton_simulate)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.macro, "")
        self.micro = QtWidgets.QWidget()
        self.micro.setObjectName("micro")
        self.gridLayout = QtWidgets.QGridLayout(self.micro)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_micro = QtWidgets.QTableWidget(self.micro)
        self.tableWidget_micro.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_micro.setObjectName("tableWidget_micro")
        self.tableWidget_micro.setColumnCount(0)
        self.tableWidget_micro.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_micro, 0, 0, 1, 1)
        self.tabWidget.addTab(self.micro, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1462, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fusion Simulator"))
        self.label_arch_settings.setText(_translate("MainWindow", "Настройки архитектуры"))
        self.label_arch_processor.setText(_translate("MainWindow", "Архитектура процессора"))
        self.comboBox_arch.setItemText(0, _translate("MainWindow", "Своя"))
        self.comboBox_arch.setItemText(1, _translate("MainWindow", "Pentium M"))
        self.comboBox_arch.setItemText(2, _translate("MainWindow", "Core 2"))
        self.comboBox_arch.setItemText(3, _translate("MainWindow", "Nehalem"))
        self.comboBox_arch.setItemText(4, _translate("MainWindow", "Sandy Bridge"))
        self.comboBox_arch.setItemText(5, _translate("MainWindow", "Ivy Bridge"))
        self.comboBox_arch.setItemText(6, _translate("MainWindow", "Haswell"))
        self.comboBox_arch.setItemText(7, _translate("MainWindow", "Broadwell"))
        self.comboBox_arch.setItemText(8, _translate("MainWindow", "Skylake"))
        self.checkBox_arch_macro.setText(_translate("MainWindow", "Макро слияние"))
        self.checkBox_arch_micro.setText(_translate("MainWindow", "Микро слияние"))
        self.label_user_arch.setText(_translate("MainWindow", "Настройки своей архитектуры"))
        self.label_user_micro.setText(_translate("MainWindow", "Микро-операции из архитектуры"))
        self.comboBox_arch_micro.setItemText(0, _translate("MainWindow", "Pentium M"))
        self.comboBox_arch_micro.setItemText(1, _translate("MainWindow", "Core 2"))
        self.comboBox_arch_micro.setItemText(2, _translate("MainWindow", "Nehalem"))
        self.comboBox_arch_micro.setItemText(3, _translate("MainWindow", "Sandy Bridge"))
        self.comboBox_arch_micro.setItemText(4, _translate("MainWindow", "Ivy Bridge"))
        self.comboBox_arch_micro.setItemText(5, _translate("MainWindow", "Haswell"))
        self.comboBox_arch_micro.setItemText(6, _translate("MainWindow", "Broadwell"))
        self.comboBox_arch_micro.setItemText(7, _translate("MainWindow", "Skylake"))
        self.label_macro_fusion_settings.setText(_translate("MainWindow", "Настройки слияния макро-операций"))
        self.label_macro_pairs_settings.setText(_translate("MainWindow", "Сливаемые пары операций"))
        self.label_macro_first_pair.setText(_translate("MainWindow", "Первая операция"))
        self.label_macro_second_pair.setText(_translate("MainWindow", "Вторая операция"))
        self.radioButton_ADD.setText(_translate("MainWindow", "ADD"))
        self.radioButton_SUB.setText(_translate("MainWindow", "SUB"))
        self.radioButton_ADC.setText(_translate("MainWindow", "ADC"))
        self.radioButton_SBB.setText(_translate("MainWindow", "SBB"))
        self.radioButton_INC.setText(_translate("MainWindow", "INC"))
        self.radioButton_DEC.setText(_translate("MainWindow", "DEC"))
        self.radioButton_CMP.setText(_translate("MainWindow", "CMP"))
        self.radioButton_TEST.setText(_translate("MainWindow", "TEST"))
        self.radioButton_AND.setText(_translate("MainWindow", "AND"))
        self.radioButton_OR.setText(_translate("MainWindow", "OR"))
        self.radioButton_XOR.setText(_translate("MainWindow", "XOR"))
        self.radioButton_NOT.setText(_translate("MainWindow", "NOT"))
        self.radioButton_NEG.setText(_translate("MainWindow", "NEG"))
        self.checkBox_JA.setText(_translate("MainWindow", "JA"))
        self.checkBox_JNA.setText(_translate("MainWindow", "JNA"))
        self.checkBox_JAE.setText(_translate("MainWindow", "JAE"))
        self.checkBox_JNAE.setText(_translate("MainWindow", "JNAE"))
        self.checkBox_JB.setText(_translate("MainWindow", "JB"))
        self.checkBox_JNB.setText(_translate("MainWindow", "JNB"))
        self.checkBox_JBE.setText(_translate("MainWindow", "JBE"))
        self.checkBox_JNBE.setText(_translate("MainWindow", "JNBE"))
        self.checkBox_JC.setText(_translate("MainWindow", "JC"))
        self.checkBox_JNC.setText(_translate("MainWindow", "JNC"))
        self.checkBox_JE.setText(_translate("MainWindow", "JE"))
        self.checkBox_JNE.setText(_translate("MainWindow", "JNE"))
        self.checkBox_JG.setText(_translate("MainWindow", "JG"))
        self.checkBox_JNG.setText(_translate("MainWindow", "JNG"))
        self.checkBox_JGE.setText(_translate("MainWindow", "JGE"))
        self.checkBox_JNGE.setText(_translate("MainWindow", "JNGE"))
        self.checkBox_JL.setText(_translate("MainWindow", "JL"))
        self.checkBox_JNL.setText(_translate("MainWindow", "JNL"))
        self.checkBox_JLE.setText(_translate("MainWindow", "JLE"))
        self.checkBox_JNLE.setText(_translate("MainWindow", "JNLE"))
        self.checkBox_JS.setText(_translate("MainWindow", "JS"))
        self.checkBox_JNS.setText(_translate("MainWindow", "JNS"))
        self.checkBox_JO.setText(_translate("MainWindow", "JO"))
        self.checkBox_JNO.setText(_translate("MainWindow", "JNO"))
        self.checkBox_JP.setText(_translate("MainWindow", "JP"))
        self.checkBox_JNP.setText(_translate("MainWindow", "JNP"))
        self.checkBox_JPO.setText(_translate("MainWindow", "JPO"))
        self.checkBox_JPE.setText(_translate("MainWindow", "JPE"))
        self.checkBox_JZ.setText(_translate("MainWindow", "JZ"))
        self.checkBox_JNZ.setText(_translate("MainWindow", "JNZ"))
        self.checkBox_JCXZ.setText(_translate("MainWindow", "JCXZ"))
        self.checkBox_JECXZ.setText(_translate("MainWindow", "JECXZ"))
        self.checkBox_JRCXZ.setText(_translate("MainWindow", "JRCXZ"))
        self.checkBox_LOOP.setText(_translate("MainWindow", "LOOP"))
        self.label_macro_first_pair_operands.setText(_translate("MainWindow", "Допустимые операнды первой операции"))
        self.checkBox_Reg_Reg.setText(_translate("MainWindow", "Регистр + Регистр"))
        self.checkBox_Reg_Imm.setText(_translate("MainWindow", "Регистр + Непосредственный операнд"))
        self.checkBox_Reg_Mem.setText(_translate("MainWindow", "Регистр + Память"))
        self.checkBox_Reg_RIP.setText(_translate("MainWindow", "Регистр + RIP-Память"))
        self.checkBox_Mem_Imm.setText(_translate("MainWindow", "Память + Непосредственный операнд"))
        self.checkBox_Reg.setText(_translate("MainWindow", "Регистр"))
        self.checkBox_Mem.setText(_translate("MainWindow", "Память"))
        self.checkBox_RIP.setText(_translate("MainWindow", "RIP-Память"))
        self.label_macro_conditions.setText(_translate("MainWindow", "Условия"))
        self.checkBox_16_Bit_Border_Start.setText(_translate("MainWindow", "Начало условного перехода на границе в 16 бит разрешено"))
        self.checkBox_16_Bit_Border_Cross.setText(_translate("MainWindow", "Пересечение условным переходом границы в 16 бит разрешено"))
        self.checkBox_Two_Pairs.setText(_translate("MainWindow", "Две пары в такт"))
        self.checkBox_Transfer.setText(_translate("MainWindow", "Перенос первой инструкции на следующий такт при попадании на последний декодер"))
        self.label_macro_mode.setText(_translate("MainWindow", "Режимы слияния"))
        self.checkBox_16_Bit_Mode.setText(_translate("MainWindow", "16 бит"))
        self.checkBox_32_Bit_Mode.setText(_translate("MainWindow", "32 бит"))
        self.checkBox_64_Bit_Mode.setText(_translate("MainWindow", "64 бит"))
        self.label_micro_fusion_settings.setText(_translate("MainWindow", "Настройки слияния микро-операций"))
        self.label_micro_pairs_settings.setText(_translate("MainWindow", "Сливамые пары операций"))
        self.checkBox_Address_Write.setText(_translate("MainWindow", "Вычисление адреса + Запись данных"))
        self.checkBox_Read_Modify.setText(_translate("MainWindow", "Чтение данных + Изменение данных"))
        self.checkBox_Read_Modify_Write.setText(_translate("MainWindow", "Чтение данных + Изменение данных + Запись данных"))
        self.label_micro_conditions.setText(_translate("MainWindow", "Условия"))
        self.checkBox_micro_Rip_Imm.setText(_translate("MainWindow", "RIP и непосредственный операнд в одной иструкции"))
        self.label_micro_operated_registers.setText(_translate("MainWindow", "Оперируемые регистры и операнды"))
        self.checkBox_micro_Reg.setText(_translate("MainWindow", "Регистры"))
        self.checkBox_micro_Mem.setText(_translate("MainWindow", "Память"))
        self.checkBox_micro_Mmx.setText(_translate("MainWindow", "MMX"))
        self.checkBox_micro_Xmm.setText(_translate("MainWindow", "XMM"))
        self.checkBox_micro_Rip.setText(_translate("MainWindow", "RIP"))
        self.checkBox_micro_Imm.setText(_translate("MainWindow", "Непосредственные операнды"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("MainWindow", "Параметры"))
        self.label_macro_template.setText(_translate("MainWindow", "Вариант готового программного кода"))
        self.pushButton_simulate.setText(_translate("MainWindow", "Моделировать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.macro), _translate("MainWindow", "Макро уровень"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.micro), _translate("MainWindow", "Микро уровень"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
